#https://docs.openshift.org/latest/architecture/core_concepts/pods_and_services.html 
apiVersion: v1
kind: Pod
metadata:
  name: simple-app
  labels:                                
    app: simple-app
spec:
  containers:                            
  - env:                                 
    - name: MY_ENV_VAR
      value: testtest
    image: docker.io/rayson/upshift-demo
    command:
        - python3
        - /app/simple-flask-app.py
    imagePullPolicy: Always
    name: my-simple-pod
    ports:                              
    - containerPort: 5000
      protocol: TCP
